// Uploads Kotan's emoji set to the bot's application emojis so commands can
// use them anywhere — server doesn't need them added. Run:
//
//   npm run emojis
//
// Sources: every *.svg in assets/emojis/ (the built-in set is generated by
// scripts/genIcons.js) is rasterized to a 128px PNG with @resvg/resvg-js —
// Discord doesn't accept SVG files as emojis. Plain images (png/jpg/gif/webp)
// in the same folder upload as-is. Filename becomes the emoji key, uploaded
// as kotan_<name>; replaces any existing emoji with that name. The resulting
// name -> "<:name:id>" map lands in src/utils/emojis.json (committed — the
// map must ship so deployments get the emojis without rerunning this).

require('dotenv').config();
const fs = require('node:fs');
const path = require('node:path');
const { Client, GatewayIntentBits } = require('discord.js');
const { Resvg } = require('@resvg/resvg-js');
const logger = require('../src/utils/logger');

const SRC_DIR = path.join(__dirname, '..', 'assets', 'emojis');
const PREVIEW_DIR = path.join(__dirname, '..', 'data', 'emojis');
const MAP_FILE = path.join(__dirname, '..', 'src', 'utils', 'emojis.json');
const SIZE = 128;

async function main() {
    if (!process.env.BOT_MAIN_TOKEN) {
        logger.error('BOT_MAIN_TOKEN missing — set it in .env first');
        process.exit(1);
    }
    fs.mkdirSync(PREVIEW_DIR, { recursive: true });

    // 1. Collect jobs: svg -> rendered png (also kept in data/emojis/ for
    //    preview), raster images -> uploaded directly.
    const jobs = {}; // emojiName -> file path
    for (const f of fs.readdirSync(SRC_DIR)) {
        const base = path.basename(f, path.extname(f)).toLowerCase().replace(/[^a-z0-9_]/g, '_');
        if (base.length < 2 || base.length > 25) continue;
        const file = path.join(SRC_DIR, f);
        if (f.endsWith('.svg')) {
            try {
                const png = new Resvg(fs.readFileSync(file, 'utf8'), {
                    fitTo: { mode: 'width', value: SIZE },
                }).render().asPng();
                const out = path.join(PREVIEW_DIR, `kotan_${base}.png`);
                fs.writeFileSync(out, png);
                jobs[`kotan_${base}`] = out;
            } catch (err) {
                logger.warn(`${f} render failed: ${err.message}`);
            }
        } else if (/\.(png|jpe?g|gif|webp)$/i.test(f)) {
            jobs[`kotan_${base}`] = file;
        }
    }

    // 2. Login and sync the application emoji set.
    const client = new Client({ intents: [GatewayIntentBits.Guilds] });
    await client.login(process.env.BOT_MAIN_TOKEN);
    const existing = await client.application.emojis.fetch();
    logger.info(`${existing.size} app emojis exist, uploading ${Object.keys(jobs).length}…`);

    // Removed designs get pruned off the app too — kotan_* emoji with no
    // matching file are deleted and dropped from the map.
    const pruned = [];
    for (const e of existing.values()) {
        if (!e.name.startsWith('kotan_') || jobs[e.name]) continue;
        await client.application.emojis.delete(e.id).catch(() => {});
        pruned.push(e.name.replace(/^kotan_/, ''));
        logger.warn(`pruned ${e.name}`);
    }

    const map = {};
    for (const [name, file] of Object.entries(jobs)) {
        try {
            const old = existing.find((e) => e.name === name);
            if (old) await client.application.emojis.delete(old.id).catch(() => {});
            const e = await client.application.emojis.create({ name, attachment: file });
            map[name.replace(/^kotan_/, '')] = `<${e.animated ? 'a' : ''}:${e.name}:${e.id}>`;
            logger.success(`${name} → ${map[name.replace(/^kotan_/, '')]}`);
        } catch (err) {
            logger.warn(`${name} failed: ${err.message}`);
        }
    }

    // Merge with whatever was already uploaded (keys we didn't touch survive),
    // minus anything we just pruned.
    let prev = {};
    try { prev = JSON.parse(fs.readFileSync(MAP_FILE, 'utf8')); } catch {}
    const merged = { ...prev, ...map };
    for (const key of pruned) delete merged[key];
    fs.writeFileSync(MAP_FILE, JSON.stringify(merged, null, 2));
    logger.success(`wrote ${Object.keys(merged).length} emoji refs to ${path.relative(process.cwd(), MAP_FILE)}`);
    client.destroy();
}

main().then(() => process.exit(0)).catch((e) => { logger.error(e); process.exit(1); });
