// Single source of truth for the dashboard command list — mirrors
// src/commands/*.js. Adding a command means adding one entry here.

module.exports = [
    { name: 'help', description: 'Lists all commands, or shows details about one command or category.', module: 'core' },
    { name: 'disable', description: 'Disable a command globally, in a channel, or during a daily time window.', module: 'config' },
    { name: 'enable', description: 'Re-enable a command — removes global or scoped disable rules.', module: 'config' },
    { name: 'balance', description: 'Shows your (or another user\'s) wallet, level and rankings.', module: 'economy' },
    { name: 'daily', description: 'Claims your daily reward. Claim every day to grow your streak.', module: 'economy' },
    { name: 'pay', description: 'Transfers coins from your wallet to another member.', module: 'economy' },
    { name: 'shop', description: 'Shows the item shop. Use "shop buy <item>" to purchase.', module: 'economy' },
    { name: 'coinflip', description: 'Flips a coin — free, against the house, or wagered against another member.', module: 'games' },
    { name: '8ball', description: 'Ask the magic 8-ball a question.', module: 'games' },
    { name: 'guess', description: 'I\'m thinking of a number 1-50 — guess it in 4 tries to win coins.', module: 'games' },
    { name: 'hilo', description: 'Bet coins, then guess whether the next card is higher or lower.', module: 'games' },
    { name: 'roll', description: 'Rolls a die. Add a bet to duel the bot — higher roll wins.', module: 'games' },
    { name: 'rps', description: 'Rock paper scissors against the bot. Optionally bet coins on it.', module: 'games' },
    { name: 'scramble', description: 'Unscramble the word — first correct answer in the channel wins coins.', module: 'games' },
    { name: 'ship', description: 'Ships you with another member — draws a card with both avatars and the match %.', module: 'games' },
    { name: 'slots', description: 'Spins the slot machine. Three of a kind pays big, a pair refunds half.', module: 'games' },
    { name: 'leaderboard', description: 'Shows the top 10 members by level.', module: 'leveling' },
    { name: 'rank', description: 'Shows your (or another member\'s) level and XP progress.', module: 'leveling' },
    { name: 'richboard', description: 'Shows the top 10 richest members by wallet.', module: 'leveling' },
    { name: 'ban', description: 'Bans a member. Also accepts a user id to ban someone who left.', module: 'moderation' },
    { name: 'delwarn', description: 'Removes one warning by id, or all warnings with "all".', module: 'moderation' },
    { name: 'lock', description: 'Locks a channel — members can no longer send messages in it.', module: 'moderation' },
    { name: 'mute', description: 'Times out a member for a given duration (e.g. 10m, 1h, 2d).', module: 'moderation' },
    { name: 'purge', description: 'Deletes a batch of recent messages in this channel. Optionally only from one member.', module: 'moderation' },
    { name: 'role', description: 'Gives a role to a member.', module: 'moderation' },
    { name: 'tempban', description: 'Bans a user for a limited time, then automatically unbans them.', module: 'moderation' },
    { name: 'unban', description: 'Unbans a user by their id.', module: 'moderation' },
    { name: 'unlock', description: 'Unlocks a channel — lifts the message restriction set by lock.', module: 'moderation' },
    { name: 'unmute', description: 'Removes a member\'s timeout.', module: 'moderation' },
    { name: 'unrole', description: 'Removes a role from a member.', module: 'moderation' },
    { name: 'warn', description: 'Warns a member and stores the warning.', module: 'moderation' },
    { name: 'warns', description: 'Lists the warnings of a member (or your own).', module: 'moderation' },
    { name: 'verify', description: 'Posts the CAPTCHA verification panel in this channel.', module: 'moderation' },
    { name: 'afk', description: 'Set your AFK status, or check who pinged you while away ("afk pings").', module: 'tools' },
    { name: 'invite', description: 'Shows the link to add Kotan to your own server.', module: 'tools' },
    { name: 'avatar', description: 'Shows a user\'s avatar in full size.', module: 'tools' },
    { name: 'banner', description: 'Shows a user\'s profile banner.', module: 'tools' },
    { name: 'color', description: 'Extracts the dominant color of an image attachment or a user\'s avatar.', module: 'tools' },
    { name: 'ping', description: 'Shows the bot\'s response time and websocket latency.', module: 'tools' },
    { name: 'serverinfo', description: 'Shows information about this server.', module: 'tools' },
    { name: 'voicemaster', description: 'Controls your personal voice channel — ".voicemaster help" lists every action.', module: 'tools' },
    { name: 'lastfm', description: 'Last.fm stats — now playing, recent tracks, top charts, profile and whoknows.', module: 'tools' },
];
